server:
  port: 8080

spring:
  application:
    name: blog-post
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/
  data:
    mongodb:
      uri: mongodb://localhost:27017/portfolio

okta:
  oauth2:
    issuer: https://dev-58955540.okta.com/oauth2/default
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid}