version: '3.9'

services:
  # <========== Gateway ==========>
  api-gateway:
    build: .
    image: api-gateway:latest
    container_name: api-gateway_container
    mem_reservation: 700m
    ports:
      - "8765:8765"
    networks:
      - portfolio
    depends_on:
      - config-server
      - eureka-server
    environment:
      - eureka.client.serviceurl.defaultzone=http://eureka-server:8761/eureka
      - spring.zipkin.base-url=http://zipkin-server:9411
  # <========== BlogPost ==========>
  blog-post:
    build: .
    image: blog-post:latest
    container_name: blog-post_container
    mem_reservation: 700m
    ports:
      - "8080:8080"
    networks:
      - portfolio
    depends_on:
      - config-server
      - eureka-server
      - mongo
    environment:
      - eureka.client.serviceurl.defaultzone=http://eureka-server:8761/eureka
      - spring.zipkin.base-url=http://zipkin-server:9411
      - spring.data.mongodb.uri=mongodb://mongo:27017/portfolio
  # <========== Notification ==========>
  notification:
    build: .
    image: notification:latest
    container_name: notification_container
    mem_reservation: 700m # Memories limit
    ports:
      - "8081:8081"
    networks:
      - portfolio
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
    environment:
      - eureka.client.serviceurl.defaultzone=http://eureka-server:8761/eureka
      - spring.zipkin.base-url=http://zipkin-server:9411
  # <========== User-Management ==========>
  user-management:
    build: .
    image: user-management:latest
    container_name: user-management_container
    mem_reservation: 700m # Memories limit
    ports:
      - "1997:1997"
    networks:
      - portfolio
    depends_on:
      - config-server
      - eureka-server
      - api-gateway
    environment:
      - eureka.client.serviceurl.defaultzone=http://eureka-server:8761/eureka
      - spring.zipkin.base-url=http://zipkin-server:9411
  # <========== Mongo ==========>
  mongo:
    build: .
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - portfolio
    ports:
      - "27017:27017"
  # <========== Server ==========>
  # <- Eureka ->
  eureka-server:
    build: .
    image: eureka-server:latest
    container_name: eureka-server_container
    mem_reservation: 700m # Memories limit
    depends_on:
      - config-server
    ports:
      - "8761:8761"
    networks:
      - portfolio
  # <- Config ->
  config-server:
    build: .
    image: config-server:latest
    container_name: config-server_container
    mem_reservation: 300m
    ports:
      - "8888:8888"
    networks:
      - portfolio
  # <========== Zipkin ==========>
  zipkin-server:
    build: .
    image: openzipkin/zipkin:latest
    mem_reservation: 300m
    container_name: zipkin_container
    ports:
      - "9411:9411"
    networks:
      - portfolio
    restart: on-failure
  # <========== Swagger UI ==========>
  swagger-ui:
    build: .
    image: swaggerapi/swagger-ui:latest
    mem_reservation: 700m
    container_name: swagger-ui_container
    ports:
      - "9999:9999"
    depends_on:
      - api-gateway
    networks:
      - portfolio

networks:
  portfolio:

volumes:
  mongodb_data_container: