server:
  port: 8765

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: BlogPostController
          uri: lb://blog-post
          predicates:
            - Path=/api/v1/blogpost**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka