server:
  port: 8765

spring:
  application:
    name: gateway
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

  cloud:
    gateway:
      routes:
        - id: BlogPostController
          uri: lb://blog-post
          predicates:
            - Path=/api/v1/blogpost**
        - id: NotificationController
          uri: lb://notification
          predicates:
            - Path=/api/v1/mail/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka