server:
  port: 8765

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411/

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BlogPostController
          uri: lb://blog-post
          predicates:
            - Path=/api/v1/blogpost
            - Path=/api/v1/blogpost/find
            - Path=/api/v1/blogpost/filter
            - Path=/api/v1/blogpost/update
        - id: NotificationController
          uri: lb://notification
          predicates:
            - Path=/api/v1/mail/**
        - id: UserManagementController
          uri: lb://user-management
          predicates:
            - Path=/api/v1/userdata**

okta:
  oauth2:
    issuer: ${OKTA_CLIENT_ISSUER}
    client-id: ${OKTA_CLIENT_ID}
    client-secret: ${OKTA_CLIENT_SECRET}
    scopes: openid, profile, email

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka